version: '3'

services:
  database:
    container_name: 'database-drizzle-trpc'
    image: 'postgres:13-alpine'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=trpc
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped